[project]
name = "ancsimulator"
version = "1.0.0"
description = "Simulate Active Noise Cancellation (ANC) systems with interactive visualizations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "librosa>=0.11.0",
    "plotly>=6.3.1",
    "streamlit>=1.50.0",
]
